In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])

#### zeros : to create an array with value of zero

In [4]:
arr_zeros = np.zeros((3, 4))

In [5]:
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones : to create an array with value filled with one

In [6]:
arr_ones = np.ones((2, 5))

In [7]:
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### full : to create an array with a specific value

In [12]:
arr = np.full((2,4), 7)

In [13]:
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

### eye : to create an identity matrix

In [15]:
mat_i = np.eye(4)

In [16]:
mat_i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### linspace : 

In [35]:
lin = np.linspace(10, 15, 11)

In [36]:
lin

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ])