In [1]:
import numpy as np

In [2]:
x = [10, 20, 30, 40, 50]

In [3]:
x

[10, 20, 30, 40, 50]

In [4]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [5]:
arr

array([10, 20, 30, 40, 50, 60])

In [6]:
print(arr)

[10 20 30 40 50 60]


In [7]:
arr

array([10, 20, 30, 40, 50, 60])

#### The difference between list and array

##### 1) Numpy arrays are faster than list
##### 2) lists are good with small amount of data

In [11]:
import time

In [14]:

start = time.time()
lst = [i for i in range(1, 1000001)]
end = time.time()

print("The time taken by list is: ", end-start)

The time taken by list is:  0.1679697036743164


In [15]:
start = time.time()
arr = np.arange(1, 1000001)
end = time.time()

print("The time taken by array is: ", end-start)

The time taken by array is:  0.008753061294555664


In [16]:
x = [1,2,3,4,5]
y = [10, 20, 30, 40, 50]

x + y

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [19]:
x_arr = np.array(x)
y_arr = np.array(y)

In [20]:
x_arr

array([1, 2, 3, 4, 5])

In [21]:
y_arr

array([10, 20, 30, 40, 50])

In [22]:
x_arr + y_arr

array([11, 22, 33, 44, 55])