In [1]:
import numpy as np

In [4]:
# Random number : 

# 1) lagacy methods : traditional methods
# 2) new generator interface : 1.17+

### rand: it generates the values between 0 and 1 with given shape

In [16]:
arr = np.random.rand(3, 2)

In [17]:
arr

array([[0.26870403, 0.67450198],
       [0.17115361, 0.33558907],
       [0.3691831 , 0.43999008]])

### randn : it generates random values in standard normal distribution

In [7]:
arr_2 = np.random.randn(3,2) 

In [8]:
arr_2

array([[-0.40353357, -1.13525898],
       [ 0.04269431, -1.07067796],
       [ 0.99327508, -0.20906717]])

### randint : it generates random values between given range, and with given shape

In [14]:
arr_3 = np.random.randint(10, 20, (3, 5))

In [15]:
arr_3

array([[16, 17, 18, 13, 12],
       [17, 10, 15, 14, 16],
       [13, 13, 18, 12, 18]], dtype=int32)

### new generator interface

In [18]:
rng = np.random.default_rng()

In [20]:
rng.random((3,4))

array([[0.84434096, 0.38592876, 0.6596844 , 0.20063885],
       [0.54808727, 0.30890843, 0.50069453, 0.92813299],
       [0.48217765, 0.44123167, 0.04863299, 0.91721499]])

In [44]:
rng.integers(low=100, high=200, size=(3, 5))

array([[120, 167, 186, 173, 154],
       [160, 140, 136, 159, 101],
       [189, 171, 106, 146, 121]])

In [56]:
rng.choice([10, 20, 30, 40, 50], size=(2,2))

array([[40, 10],
       [50, 30]])