In [1]:
# Scalar, vector, matrix, and tensor

In [2]:
import numpy as np

#### Scalar : is a single value without any dimension
#### vector : goes into one direction and it has one dimension
#### matrix : goes into two direction and it has two dimension (row and column)
#### tensor : >= 3 dimensions

In [3]:
a = 10

In [4]:
x = np.array([1,2,3,4,5])

In [5]:
x

array([1, 2, 3, 4, 5])

In [6]:
matrix = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

In [7]:
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
tensor = np.array([
    [
        [1,2,3],
        [3,4,5],
    ],
    [
        [1,2,3],
        [3,4,5],
    ],
])

In [9]:
tensor

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])