In [1]:
import numpy as np

In [8]:
x = np.array([12, 21, 34, 32, 21, 22, 45, 42, 46, 30, 70, 40])

In [9]:
x

array([12, 21, 34, 32, 21, 22, 45, 42, 46, 30, 70, 40])

In [10]:
# you can sort your original array

# x.sort()

In [11]:
x

array([12, 21, 34, 32, 21, 22, 45, 42, 46, 30, 70, 40])

In [12]:
sorted_arr = np.sort(x)

In [13]:
sorted_arr

array([12, 21, 21, 22, 30, 32, 34, 40, 42, 45, 46, 70])

In [15]:
sorted_arr[::-1]

array([70, 46, 45, 42, 40, 34, 32, 30, 22, 21, 21, 12])

In [16]:
# argsort

In [17]:
# sorting values by indices
np.argsort(x)

array([ 0,  1,  4,  5,  9,  3,  2, 11,  7,  6,  8, 10])

In [18]:
x

array([12, 21, 34, 32, 21, 22, 45, 42, 46, 30, 70, 40])

In [ ]:
12, 21, 21, 22, 30